# Generated by Django 5.2.6 on 2025-09-20 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_slug', models.SlugField(max_length=200, unique=True)),
                ('priduct_description', models.TextField(blank=True, max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='photos/products')),
                ('product_stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_updated_date', models.DateTimeField(auto_now=True)),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
