# Generated by Django 5.2.6 on 2025-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(auto_created=True, help_text='a label for URL config', max_length=200, unique=True),
        ),
    ]
