# Generated by Django 5.2.6 on 2025-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_slug', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, max_length=300)),
                ('category_img', models.ImageField(blank=True, upload_to='photos/category/')),
                ('category_created_date', models.DateTimeField(auto_now_add=True)),
                ('category_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
